version: "3.8"

services:
  qubox-message-bus:
    image: "qubox/message-bus:${QUBOX_DOCKER_TAG:?Must set env var QUBOX_DOCKER_TAG}"
    networks:
      - qubox-net
    hostname: "qubox-message-bus"
    ports:
      - "${QUBOX_BIND_ADDRESS}:${QUBOX_PORT_RABBITMQ:?Must set env var QUBOX_PORT_RABBITMQ}:5672"
      - "${QUBOX_BIND_ADDRESS}:${QUBOX_PORT_RABBITMQ_MANAGEMENT:?Must set env var QUBOX_PORT_RABBITMQ_MANAGEMENT}:15672"
      - "${QUBOX_BIND_ADDRESS}:${QUBOX_PORT_WEBSOCKET:?Must set env var QUBOX_PORT_WEBSOCKET}:4000"
    restart: "unless-stopped"
    healthcheck:
      test: rabbitmq-diagnostics -q is_running
      interval: 10s
      timeout: 30s
      retries: 3

  qubox-registry:
    image: "qubox/registry:${QUBOX_DOCKER_TAG:?Must set env var QUBOX_DOCKER_TAG}"
    volumes:
      - ./shared_files:/mnt/shared_files
      - qubox_registry_data:/home/app/
    ports:
      - "${QUBOX_BIND_ADDRESS}:${QUBOX_PORT_QUBOX_REGISTRY:?Must set env var QUBOX_PORT_QUBOX_REGISTRY}:8000"
    depends_on:
      qubox-message-bus:
        condition: service_healthy
    environment:
      QUBOX_RABBITMQ_QUEUE_NAME: "qubox_registry"
      QUBOX_HOST_RABBITMQ: "qubox-message-bus"
      QUBOX_PORT_RABBITMQ: "5672"
      QUBOX_REGISTRY_SERVER_DB_PATH: "/home/app/qubox_registry_database.db"
    networks:
      - qubox-net
    restart: "unless-stopped"

  qubox-frontend:
    image: qubox/frontend:${QUBOX_DOCKER_TAG:?Must set env var QUBOX_DOCKER_TAG}
    ports:
      - "${QUBOX_BIND_ADDRESS}:${QUBOX_PORT_QUBOX_FRONTEND:?Must set env var QUBOX_PORT_QUBOX_FRONTEND}:12000"
    networks:
      - qubox-net
    restart: "unless-stopped"
    environment:
        # Fixes bug where websocket connection is fixed to default port 3000.
        # See: https://github.com/facebook/create-react-app/issues/11779#issuecomment-1199085393
        - WDS_SOCKET_PORT=0

  xharpy-gpaw:
    image: "qubox/xharpy-gpaw:${QUBOX_DOCKER_TAG:?Must set env var QUBOX_DOCKER_TAG}"
    environment:
      QUBOX_RABBITMQ_QUEUE_NAME: "xharpy-gpaw"
      QUBOX_APPLICATION_CONFIG_FILE: "configure_xharpy.py"
    volumes:
      - ./shared_files:/mnt/shared_files
    depends_on:
      - qubox-registry
    networks:
      - qubox-net
    restart: "unless-stopped"

  nosphera2-pyscf:
    image: "qubox/nosphera2_pyscf:${QUBOX_DOCKER_TAG:?Must set env var QUBOX_DOCKER_TAG}"
    environment:
      QUBOX_RABBITMQ_QUEUE_NAME: "nosphera2_pyscf"
      QUBOX_APPLICATION_CONFIG_FILE: "configure_nosphera2-pyscf.py"
    volumes:
      - ./shared_files:/mnt/shared_files
    depends_on:
      - qubox-registry
    networks:
      - qubox-net
    restart: "unless-stopped"

  crysalis-pro:
    image: qubox/crysalis-pro:${QUBOX_DOCKER_TAG:?Must set env var QUBOX_DOCKER_TAG}
    volumes:
      - ./shared_files:/mnt/shared_files
      - wine_installations_dir:/opt/wine_installations
    networks:
      - qubox-net
    ports:
      - "${QUBOX_BIND_ADDRESS}:${QUBOX_PORT_CRYSALIS_PRO:?Must set env var QUBOX_PORT_CRYSALIS_PRO}:8080"
    depends_on:
      - qubox-registry
    restart: "unless-stopped"
    environment:
      QUBOX_APP_DISPLAY_NAME: "CrysAlis Pro"
      SHARED_FILES_DIR: /mnt/shared_files
      QUBOX_RABBITMQ_QUEUE_NAME: "crysalis-pro"
      QUBOX_APPLICATION_CONFIG_FILE: "configure_crysalis_pro.py"

  olex2-linux:
    image: qubox/olex2-linux:${QUBOX_DOCKER_TAG:?Must set env var QUBOX_DOCKER_TAG}
    volumes:
      - ./shared_files:/mnt/shared_files
    networks:
      - qubox-net
    ports:
      - "${QUBOX_BIND_ADDRESS}:${QUBOX_PORT_OLEX2_LINUX:?Must set env var QUBOX_PORT_OLEX2_LINUX}:8080"
    depends_on:
      - qubox-registry
    restart: unless-stopped
    environment:
      QUBOX_APP_DISPLAY_NAME: "Olex2"
      QUBOX_APPLICATION_CONFIG_FILE: "configure_olex2.py"
      SHARED_FILES_DIR: /mnt/shared_files

  crystal-explorer:
    image: qubox/crystal-explorer:${QUBOX_DOCKER_TAG:?Must set env var QUBOX_DOCKER_TAG}
    volumes:
      - ./shared_files:/mnt/shared_files
    networks:
      - qubox-net
    ports:
      - "${QUBOX_BIND_ADDRESS}:${QUBOX_PORT_CRYSTAL_EXPLORER:?Must set env var QUBOX_PORT_CRYSTAL_EXPLORER}:8080"
    depends_on:
      - qubox-registry
    restart: "unless-stopped"
    environment:
      QUBOX_APP_DISPLAY_NAME: "CrystalExplorer"
      QUBOX_APPLICATION_CONFIG_FILE: "configure_crystal_explorer.py"
      SHARED_FILES_DIR: /mnt/shared_files

networks:
  qubox-net:

volumes:
  qubox_registry_data:
  wine_installations_dir:
